# Generated by Django 3.2.5 on 2021-07-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarRect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectangle',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rectangle',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
